In [2]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as smp
from sympy.vector import *
from scipy.integrate import quad, quad_vec

plt.style.use("ggplot")

In [3]:
x, y, z, u1, u2, u3, v1, v2, v3, t = smp.symbols("x y z u_1 u_2 u_3 v_1 v_2 v_3 t")

# Vectors and Geometry

Numerical or symbolic

In [4]:
a = np.array([1,2,3])
b = np.array([7,8,9])
u = smp.Matrix([u1, u2, u3])
v = smp.Matrix([v1, v2, v3])

In [11]:
u.subs([(u1, 3)])

Matrix([
[  3],
[u_2],
[u_3]])

## Addition & multiplication

In [12]:
2*(a + b)

array([16, 20, 24])

In [13]:
2 * (u + v)

Matrix([
[2*u_1 + 2*v_1],
[2*u_2 + 2*v_2],
[2*u_3 + 2*v_3]])

## Dot products

In [14]:
np.dot(a, b)

50

In [15]:
u.dot(v)

u_1*v_1 + u_2*v_2 + u_3*v_3

## Cross products

In [16]:
np.cross(a, b)

array([-6, 12, -6])

In [17]:
u.cross(v)

Matrix([
[ u_2*v_3 - u_3*v_2],
[-u_1*v_3 + u_3*v_1],
[ u_1*v_2 - u_2*v_1]])

## Length of vector

In [18]:
np.linalg.norm(a)

3.7416573867739413

In [19]:
u.norm()

sqrt(Abs(u_1)**2 + Abs(u_2)**2 + Abs(u_3)**2)

## Vector projection

$$\text{proj}_v (u) = \frac{u.v}{|v|^2 } u$$

In [21]:
proj_b_a = np.dot(a,b)/np.linalg.norm(b)**2 * b
proj_b_a

array([1.80412371, 2.06185567, 2.31958763])

In [23]:
proj_u_v = u.dot(v)/v.norm()**2 *u 
proj_u_v

Matrix([
[u_1*(u_1*v_1 + u_2*v_2 + u_3*v_3)/(Abs(v_1)**2 + Abs(v_2)**2 + Abs(v_3)**2)],
[u_2*(u_1*v_1 + u_2*v_2 + u_3*v_3)/(Abs(v_1)**2 + Abs(v_2)**2 + Abs(v_3)**2)],
[u_3*(u_1*v_1 + u_2*v_2 + u_3*v_3)/(Abs(v_1)**2 + Abs(v_2)**2 + Abs(v_3)**2)]])

## Lines/Planes in space

Lines: $$
\vec{r}(t) = \vec{r}_0 + t\vec{v}
$$

In [24]:
r0 = smp.Matrix([1,1,1])
v = smp.Matrix([1,3,-1])
r = r0 + t*v
r

Matrix([
[  t + 1],
[3*t + 1],
[  1 - t]])

Planes:
$$
\vec{n}.(P_0 - <x, y, z>) = 0
$$

In [26]:
P0 = smp.Matrix([4,4,8])
r = smp.Matrix([x,y,z])
n = smp.Matrix([1,1,1])
n.dot(P0 - r) # = 0

-x - y - z + 16

**Examples**: Find vector parallel to the line of intersection of the two planes $3x - 6y-2z=15$ and $2x +y -2z = 5$ (it's going to be perpendicular to both normal vectors).

In [27]:
n1 = np.array([3, -6, -2])
n2 = np.array([2, 1, -2])
ans = np.cross(n1,n2)
ans

array([14,  2, 15])

# Vector Calculus

## Vector Derivatives

In [28]:
r = smp.Matrix([3*t, smp.sin(t), t**2])
r

Matrix([
[   3*t],
[sin(t)],
[  t**2]])