# Defining matrix

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3], [4,5,6]])

In [3]:
x.shape

(2, 3)

In [5]:
np.random.randint(0,10,(2,3))
# 0 - 10, size: 2 x 3

array([[1, 8, 1],
       [1, 1, 2]])

# Matrix Arithmetic

## Addition

In [6]:
np.random.seed(0)

In [9]:
a = np.random.randint(1, 100, (5,4))
b = np.random.randint(1, 100, (5,4))
print(a)
print("\n")
print(b)

[[80  5 43 59]
 [32  2 66 42]
 [58 36 12 47]
 [83 92  1 15]
 [54 13 43 85]]


[[76 69  7 69]
 [48  4 77 53]
 [79 16 21 59]
 [24 80 14 86]
 [49 50 70 42]]


In [10]:
a + b

array([[156,  74,  50, 128],
       [ 80,   6, 143,  95],
       [137,  52,  33, 106],
       [107, 172,  15, 101],
       [103,  63, 113, 127]])

In [15]:
c = np.arange(1,3)
print(c)