# Defining matrix

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3], [4,5,6]])

In [3]:
x.shape

(2, 3)

In [4]:
np.random.randint(0,10,(2,3))
# 0 - 10, size: 2 x 3

array([[1, 0, 3],
       [3, 7, 7]])

# Matrix Arithmetic

## Addition

In [5]:
np.random.seed(0)

In [6]:
a = np.random.randint(1, 100, (5,4))
b = np.random.randint(1, 100, (5,4))
print(a)
print("\n")
print(b)

[[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]
 [40 88 47 89]]


[[82 38 26 78]
 [73 10 21 81]
 [70 80 48 65]
 [83 89 50 30]
 [20 20 15 40]]


In [7]:
a + b

array([[127,  86,  91, 146],
       [141,  20, 105, 103],
       [107, 168, 119, 154],
       [172, 102, 109,  96],
       [ 60, 108,  62, 129]])

In [10]:
c = np.arange(1,3)
c

array([1, 2])

In [11]:
a + c

ValueError: operands could not be broadcast together with shapes (5,4) (2,) 

## Subtraction

In [12]:
a

array([[45, 48, 65, 68],
       [68, 10, 84, 22],
       [37, 88, 71, 89],
       [89, 13, 59, 66],
       [40, 88, 47, 89]])

In [13]:
b

array([[82, 38, 26, 78],
       [73, 10, 21, 81],
       [70, 80, 48, 65],
       [83, 89, 50, 30],
       [20, 20, 15, 40]])

In [14]:
a - b

array([[-37,  10,  39, -10],
       [ -5,   0,  63, -59],
       [-33,   8,  23,  24],
       [  6, -76,   9,  36],
       [ 20,  68,  32,  49]])

## Matrix division

In [15]:
a / b

array([[0.54878049, 1.26315789, 2.5       , 0.87179487],
       [0.93150685, 1.        , 4.        , 0.27160494],
       [0.52857143, 1.1       , 1.47916667, 1.36923077],
       [1.07228916, 0.14606742, 1.18      , 2.2       ],
       [2.        , 4.4       , 3.13333333, 2.225     ]])

## Multiplication - Hadamard

$A \bigodot B$

In [17]:
A = np.random.randint(1,10,(2,2))
A

array([[8, 4],
       [3, 8]])

In [18]:
B = np.random.randint(1,10,(2,2))
B

array([[3, 1],
       [1, 5]])

In [19]:
A * B

array([[24,  4],
       [ 3, 40]])

## Matrix multiplication

In [20]:
A

array([[8, 4],
       [3, 8]])

In [21]:
B

array([[3, 1],
       [1, 5]])

In [22]:
np.matmul(A, B)

array([[28, 28],
       [17, 43]])

In [23]:
A @ B

array([[28, 28],
       [17, 43]])

In [24]:
np.dot(A, B)

array([[28, 28],
       [17, 43]])

## Matrix vector multiplication

In [26]:
A = np.random.randint(10, 100, (4,4))
A

array([[92, 10, 24, 63],
       [22, 52, 94, 85],
       [78, 16, 78, 57],
       [13, 86, 62, 88]])

In [28]:
b = np.arange(2,6)
b

array([2, 3, 4, 5])

In [30]:
output_vec = A.dot(b)
output_vec

array([ 625, 1001,  801,  972])

## Matrix scalar multiplication

In [31]:
A

array([[92, 10, 24, 63],
       [22, 52, 94, 85],
       [78, 16, 78, 57],
       [13, 86, 62, 88]])

In [32]:
2*A

array([[184,  20,  48, 126],
       [ 44, 104, 188, 170],
       [156,  32, 156, 114],
       [ 26, 172, 124, 176]])

# Types of Matrices