# Arrays, Matrices, \& Tensors

Arrays are the most powerful and useful features in Julia. Let's start with some basics

In [23]:
students = ["Jack", "Jill", "John"]

3-element Vector{String}:
 "Jack"
 "Jill"
 "John"

In [24]:
typeof(students)

Vector{String} (alias for Array{String, 1})

String defines the type of the elements and 1 is the dimension of the array

In [25]:
fib = [1,1,2,3,5,8,13]

7-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13

In [26]:
typeof(fib)

Vector{Int64} (alias for Array{Int64, 1})

In [27]:
push!(fib,21)

8-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13
 21

In [28]:
@show fib;

fib = [1, 1, 2, 3, 5, 8, 13, 21]


## 2D arrays

In [29]:
mat = [
    [1,2,3],
    [4,5,6],
    [7,8,9, 24]
]

3-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5, 6]
 [7, 8, 9, 24]

In [30]:
typeof(mat)

Vector{Vector{Int64}} (alias for Array{Array{Int64, 1}, 1})

Notice this type! It's not a 2D matrix. It's a 1D array but each element within it's a 1D array itself! These are useful in certain cases, but we are usually interested in 2D arrays in data sci and ML

Let's create a 2D array!

## Matrices

In [31]:
x = [1 2 3] # notice the lack of commas (and the dimensions)

1×3 Matrix{Int64}:
 1  2  3

In [32]:
x' # tur this into a column vector

3×1 adjoint(::Matrix{Int64}) with eltype Int64:
 1
 2
 3

In [33]:
mat = [
    [1 2 3]
    [4 5 6]
    [7 8 9]
    ]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [34]:
typeof(mat)

Matrix{Int64} (alias for Array{Int64, 2})

In [35]:
typeof(x')

LinearAlgebra.Adjoint{Int64, Matrix{Int64}}

## Size (shapes) \& reshaping

In [36]:
size(mat) # extremely important in ML

(3, 3)

In [37]:
mat

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [38]:
fib

8-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13
 21

In [39]:
size(fib) # important difference

(8,)

In [40]:
X =[
    [1 2 3]
    [4 5 6]
    [7 8 9]
    [10 11 12]
    ]

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

In [41]:
size(X)

(4, 3)

In [42]:
X = reshape(X, 2, 6) # left top -> bottom -> to the right

2×6 Matrix{Int64}:
 1   7  2   8  3   9
 4  10  5  11  6  12

In [43]:
X = reshape(X, 12, 1)

12×1 Matrix{Int64}:
  1
  4
  7
 10
  2
  5
  8
 11
  3
  6
  9
 12

In [44]:
X = reshape(X, 4, 3)

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

## Helper Functions

## Creating random matrices

In [45]:
rand(4, 3) # uniformly dist. from 0 to 1

4×3 Matrix{Float64}:
 0.504242  0.229586  0.973778
 0.183449  0.701572  0.535683
 0.88258   0.336429  0.451542
 0.780917  0.359069  0.556921

In [46]:
mat = rand(4, 3)

4×3 Matrix{Float64}:
 0.675407   0.547227  0.600307
 0.184772   0.969489  0.986244
 0.315809   0.830268  0.0926124
 0.0164351  0.610327  0.0339165

In [47]:
mat2 = mat;

In [48]:
mat2[1,1] = 100

100

In [49]:
mat2

4×3 Matrix{Float64}:
 100.0        0.547227  0.600307
   0.184772   0.969489  0.986244
   0.315809   0.830268  0.0926124
   0.0164351  0.610327  0.0339165

In [50]:
mat

4×3 Matrix{Float64}:
 100.0        0.547227  0.600307
   0.184772   0.969489  0.986244
   0.315809   0.830268  0.0926124
   0.0164351  0.610327  0.0339165

## Copying arrays

In [51]:
mat3 = copy(mat)

4×3 Matrix{Float64}:
 100.0        0.547227  0.600307
   0.184772   0.969489  0.986244
   0.315809   0.830268  0.0926124
   0.0164351  0.610327  0.0339165

In [52]:
mat3[1,1] = 9999

9999

In [53]:
mat3

4×3 Matrix{Float64}:
 9999.0        0.547227  0.600307
    0.184772   0.969489  0.986244
    0.315809   0.830268  0.0926124
    0.0164351  0.610327  0.0339165

In [54]:
mat

4×3 Matrix{Float64}:
 100.0        0.547227  0.600307
   0.184772   0.969489  0.986244
   0.315809   0.830268  0.0926124
   0.0164351  0.610327  0.0339165

## Comprehensions

We can also do nested loops with comprehensions

In [55]:
[i for i in 1:5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [56]:
[(i,j) for i in 1:5, j in 6:10]

5×5 Matrix{Tuple{Int64, Int64}}:
 (1, 6)  (1, 7)  (1, 8)  (1, 9)  (1, 10)
 (2, 6)  (2, 7)  (2, 8)  (2, 9)  (2, 10)
 (3, 6)  (3, 7)  (3, 8)  (3, 9)  (3, 10)
 (4, 6)  (4, 7)  (4, 8)  (4, 9)  (4, 10)
 (5, 6)  (5, 7)  (5, 8)  (5, 9)  (5, 10)

In [57]:
[(i^2, j) for i in 1:5, j in 6:10]

5×5 Matrix{Tuple{Int64, Int64}}:
 (1, 6)   (1, 7)   (1, 8)   (1, 9)   (1, 10)
 (4, 6)   (4, 7)   (4, 8)   (4, 9)   (4, 10)
 (9, 6)   (9, 7)   (9, 8)   (9, 9)   (9, 10)
 (16, 6)  (16, 7)  (16, 8)  (16, 9)  (16, 10)
 (25, 6)  (25, 7)  (25, 8)  (25, 9)  (25, 10)

## Matrix operations

In [58]:
A = rand(10:20, 3,3)

3×3 Matrix{Int64}:
 12  17  16
 12  10  15
 12  17  12

In [59]:
A = rand(10.:20, 3,3)

3×3 Matrix{Float64}:
 10.0  18.0  19.0
 14.0  12.0  17.0
 13.0  19.0  20.0

Instead of random values, we can provide a specific value using the fill method

In [61]:
x = fill(10.0,(3,))

3-element Vector{Float64}:
 10.0
 10.0
 10.0

In [62]:
A*x
# this is a usual matrix-vector multiplication
# of course, this requires a 'size match'

3-element Vector{Float64}:
 470.0
 430.0
 520.0

## Transpose. Trace, Determinant

In [63]:
A

3×3 Matrix{Float64}:
 10.0  18.0  19.0
 14.0  12.0  17.0
 13.0  19.0  20.0

In [64]:
A'

3×3 adjoint(::Matrix{Float64}) with eltype Float64:
 10.0  14.0  13.0
 18.0  12.0  19.0
 19.0  17.0  20.0

In [65]:
A' * A

3×3 Matrix{Float64}:
 465.0  595.0   688.0
 595.0  829.0   926.0
 688.0  926.0  1050.0

In [66]:
A'A # shortcut... typical with Julia

3×3 Matrix{Float64}:
 465.0  595.0   688.0
 595.0  829.0   926.0
 688.0  926.0  1050.0

In [73]:
using LinearAlgebra

In [74]:
tr(A) # the trace of A

42.0

In [75]:
det(A)

198.00000000000006

In [76]:
inv(A)

3×3 Matrix{Float64}:
 -0.419192   0.00505051   0.393939
 -0.29798   -0.237374     0.484848
  0.555556   0.222222    -0.666667

## Solving linear eqns. directly

In [77]:
A = rand(3,3)

3×3 Matrix{Float64}:
 0.0533341  0.0221312  0.120322
 0.0940522  0.340611   0.367552
 0.875304   0.600737   0.42929

In [78]:
x

3-element Vector{Float64}:
 10.0
 10.0
 10.0

In [79]:
b = A*x

3-element Vector{Float64}:
  1.9578764392085413
  8.022145943068885
 19.053311437468796

In [81]:
A\b # solve for x

3-element Vector{Float64}:
 10.000000000000002
  9.999999999999995
 10.0

## More...

We can create n-dim arrays easily too. These tensors will come in handy when we get to machine learning.

In [82]:
rand(4, 3, 2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.0537615  0.723029   0.685507
 0.342268   0.0683903  0.019689
 0.325498   0.712227   0.910353
 0.503248   0.238122   0.86209

[:, :, 2] =
 0.866289  0.663898   0.952733
 0.272297  0.901953   0.922882
 0.684508  0.0249539  0.588933
 0.484263  0.0811747  0.130661