# Basic Functional Programming

Functional programming is very useful when thinking in terms of mathematics. It's also massively parallelizable and you really should learn the concepts. Here, we'll take a lokk at some basics.

## Map

Map applies a function to all elements of a collection

In [1]:
collection = [1,2,4]

3-element Vector{Int64}:
 1
 2
 4

In [2]:
map(x -> x^2, collection)

3-element Vector{Int64}:
  1
  4
 16

In [3]:
squares = map(x -> x^2, collection)

3-element Vector{Int64}:
  1
  4
 16

In [4]:
@show squares

squares = [1, 4, 16]


3-element Vector{Int64}:
  1
  4
 16

`map` is, therefore a higher-order-function since it takes in a function as it's argument. Functional programming revolves around this very concept. It's very useful since, as you can see, it can be parallelized. There are complete algorithms that solve many common problems using functional programming concepts such as `map`, `reduce`, and `filter`.

## Reduce

In [5]:
collection = [1,2,4]

3-element Vector{Int64}:
 1
 2
 4

In [6]:
reduce(*, collection) # applies the * to all elements

8

We'll leave the rest of this for you to explore when you need this. We need to move to something much more relevant to Julia and our course of action.

## Broadcast

In [7]:
collection

3-element Vector{Int64}:
 1
 2
 4

In [8]:
function f(x)
    x^2
end

f (generic function with 1 method)

In [9]:
broadcast(f, collection) # seems similar to map

3-element Vector{Int64}:
  1
  4
 16

In [10]:
collection # not change

3-element Vector{Int64}:
 1
 2
 4

In [11]:
f.(collection) # it's so useful, it has a shortcut

3-element Vector{Int64}:
  1
  4
 16

In [12]:
f(collection) # this doesn't work because you can't square an array

LoadError: MethodError: no method matching ^(::Vector{Int64}, ::Int64)
Closest candidates are:
  ^(::Union{AbstractChar, AbstractString}, ::Integer) at strings/basic.jl:730
  ^(::Complex{<:AbstractFloat}, ::Integer) at complex.jl:860
  ^(::Complex{<:Integer}, ::Integer) at complex.jl:862
  ...

Let's see how a broadcast call is different from a normal call

In [13]:
M = ones(3,3)

3×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [16]:
f(M) # this is M^2, which is M*M

3×3 Matrix{Float64}:
 3.0  3.0  3.0
 3.0  3.0  3.0
 3.0  3.0  3.0

In [19]:
f.(M) # this applies x^2 to each element separately

3×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [22]:
A = [
    [1 2 3]
    [4 5 6]
    [7 8 9]
]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [24]:
A .+ 1 # apply + 1 to each element separately

3×3 Matrix{Int64}:
 2  3   4
 5  6   7
 8  9  10

In [25]:
A .* 2

3×3 Matrix{Int64}:
  2   4   6
  8  10  12
 14  16  18

In [26]:
# or even
2A

3×3 Matrix{Int64}:
  2   4   6
  8  10  12
 14  16  18